Feat/auth mock
Pet-Plat/Pet-Platform-Front pull request #10
Opened 2024-08-11 16:26 UTC by nikita-nn

# Ключевые изменения

а) Добавлена базовая функциональность входа в личный кабинет - нужна поддержка c бэка
б) Сверстан личный кабинет пользователя

2024-08-21 22:19 UTC, Vladislav0Art requested changes

2024-08-21 22:19 UTC, Vladislav0Art commented on src/providers/UserProvider.tsx
> +        setReady(true);
Тут тоже асинхронно все делается. Надо синхронизацию добавлять между `setUser` и `setReady`.

2024-08-21 22:19 UTC, Vladislav0Art commented on src/styles/globals.css
> +    @apply font-bold lg:text-2xl  text-lg;
Тут не нужно делать изменений. Я привел в порядок стили в globals.css в этом PR'e #8.

2024-08-21 22:19 UTC, Vladislav0Art commented on src/styles/globals.css
> +    @apply font-bold lg:text-2xl  text-lg;
Или это со старого коммита ветки `vartiukhov/feature/footer-components` идет? Надо #8 вмержить, чтобы только твой diff показывался.

2024-08-21 22:19 UTC, Vladislav0Art commented on src/views/pages/ClientArea.tsx
> +          className={"absolute -z-10 right-0 -top-24  lg:hidden w-full"}
**Nitpick**: А зачем `lg:hidden`? на главной glow у нас все время. Тут тож можно.

2024-08-21 22:19 UTC, Vladislav0Art commented on src/providers/UserProvider.tsx
> +  contacts: Array<Partial<Record<keyof ContactsKeys, string>>>;
Почему `Partial<ContactsKeys>` не подойдет?

2024-08-21 22:19 UTC, Vladislav0Art commented on src/views/pages/ClientArea.tsx
> +                <p>{Object.values(contact)[0]}</p>
Для:
```js
Object.keys(contact)[0]
Object.values(contact)[0]
```
Почему именно нулевой элемент ключей/значений берем? почему считаем, что он всегда есть?

2024-08-21 22:19 UTC, Vladislav0Art commented on src/views/pages/ClientArea.tsx
> +        <MainButton className={"mt-7"}>Выбрать pet проект</MainButton>
Любой conditional rendering DOM-элементов с nested элементами лучше делать через компонент (сделать non-exported компонент в этом же файле). не читаемо выглядит.

2024-08-21 22:21 UTC, nikita-nn commented on src/providers/UserProvider.tsx
> +  last_name: string;
Да

2024-08-21 22:22 UTC, nikita-nn commented on src/providers/UserProvider.tsx
> +      resolve(MockUser);
Пока у нас нет запроса данных с бэка - пусть будет затычка

2024-08-21 22:22 UTC, nikita-nn commented on src/providers/UserProvider.tsx
> +        resolve(MockUser);
Тоже самое

2024-08-21 22:24 UTC, nikita-nn commented on src/providers/UserProvider.tsx
> +        setReady(true);
Ошибаешься

setReady(true) запустится чуть чуть позже чем setUser

Следовательно отработает до конца позже чем данные о юзере будут сетнуты

2024-08-21 22:27 UTC, nikita-nn commented on src/views/pages/ClientArea.tsx
> +                <p>{Object.values(contact)[0]}</p>
Object.keys - тип Array 

подразумевается что мы берем первый элемент в случае если их пришло >1

По второму комментарию
arr = []
console.log(arr[0])

Вывод: undefined - даже если не прийдет ничего приложение не сломается - мое решение , сокращение количества строк

2024-08-21 22:30 UTC, nikita-nn commented on src/App.tsx
> +  const { user, ready } = useUserData();
Просто флаг готовности к считыванию данных

2024-08-21 22:32 UTC, nikita-nn commented on src/styles/globals.css
> +    @apply font-bold lg:text-2xl  text-lg;
Да, нужно вмерджить

Stage у нас лысый сейчас

2024-08-21 22:35 UTC, nikita-nn commented on src/providers/UserProvider.tsx
> +  contacts: Array<Partial<Record<keyof ContactsKeys, string>>>;
keyof - ключи типа

Так мы достигнем более строгой типизации

https://www.typescriptlang.org/docs/handbook/2/keyof-types.html

2024-08-24 17:50 UTC, nikita-nn commented on src/App.tsx
> +              element: <ClientArea />,
clientarea это обобщенное название) Часто используется в финтече США и на готовых банковских движках

2024-08-24 17:52 UTC, nikita-nn commented on package.json
> +  "version": "0.1.3",
версионирование в данном случае сделано не для удобства разработки , а для тегов для докер имейджев

Под каждый тег версии на гитхабе будет собираться свой образ - тем самым мы сможем откатывать стейдж или мастер на определенный коммит без костылей и заплаток 

То есть на тачку будет разливаться не latest имейдж а имейдж равный последней версии в тегах гита

2024-08-24 17:56 UTC, nikita-nn commented on src/views/pages/ClientArea.tsx
> +          className={"absolute -z-10 right-0 -top-24  lg:hidden w-full"}
в фигме как помню это разные glow выглядящие по разному

Можно конечно было пкшный глоу порезать и использовать - но тогда 100% соответствие с макетом не достигается)

2024-08-25 06:28 UTC, Vladislav0Art commented on src/providers/UserProvider.tsx
> +      resolve(MockUser);
Оставь тогда TODO или как issue на GitHub.

2024-08-30 07:16 UTC, Vladislav0Art commented on package.json
> +  "version": "0.1.3",
> откатывать стейдж или мастер на определенный коммит без костылей и заплаток

На произвольный определенный коммит откатывать не сможем -- мы как squash-merge ветки мержим, у нас промежуточные коммиты (в том числе с изменением версии), не сохраняются в истории. Чтобы описанного эффекта добиться, image'ы нужно делать в feature-ветках сразу после изменения версии до merge'а.

Например, после merge'а данного PR'а, мы никогда не сможем сделать image для версии 1.0.4, что идет в коммите [5ed3f4a](https://github.com/Pet-Plat/Pet-Platform-Front/pull/10/commits/5ed3f4a5b9ecfdf8db26f86d60f46e958e68f525); он засквошится.

2024-08-30 07:26 UTC, Vladislav0Art commented on src/components/ui/custom/button.main.tsx
> +          "w-full md:max-w-none md:w-auto text-md",
Женя сделала кнопки на всю ширину страницы. Надо будет поправить на landing'е в след. PR'ах.

2024-08-30 07:30 UTC, Vladislav0Art commented on src/providers/UserProvider.tsx
> +      resolve(MockUser);
Оставил TODO'шки две.

2024-08-30 07:43 UTC, Vladislav0Art commented on src/providers/UserProvider.tsx
> +        setReady(true);
> запустится чуть чуть позже чем setUser

Это звучит как выводы на пальцах.

Лишь потому что они асинхронные, уже нет гарантии когда кто выполнится. Вот [тут](https://stackoverflow.com/questions/56247433/how-to-use-setstate-callback-on-react-hooks) есть рецепт как сделать правильное обновление `ready` при изменении `user`, используя `useEffect`. Более того, он у тебя уже используется:
```typescript
useEffect(() => {
    setReady(true);
    // ready if user successfully changed
  }, [user]);
```
Все, что тебе надо добавить -- пару if-ов на `null`/не `null` и все.

Либо как в комментарии выше, сделать через `Promise`. Текущее решение не приму. Ты и сам видишь, что оно формально некорректное.

2024-08-30 07:53 UTC, Vladislav0Art requested changes
Один коммент про асинхронность `setState` важный остался и все. Его прям must-have поправить. После можно мержить; заребейзить только нужно.

2024-09-12 20:56 UTC, Vladislav0Art approved these changes
Давай сейчас вмержим, что есть. Любые доработки - потом.

2024-09-14 13:46 UTC, Vladislav0Art commented
Rebased on `stage`.

2024-09-14 13:47 UTC, merged