[Draft] Implement "How It Works" and "Pet-projects Gallery" sections
Pet-Plat/Pet-Platform-Front pull request #4
Opened 2024-07-29 08:25 UTC by Vladislav0Art

2024-08-01 07:59 UTC, nikita-nn requested changes

2024-08-01 07:59 UTC, nikita-nn commented on src/components/common/pet-project/PetProjectCard.tsx
> +            <div className="flex justify-between items-center gap-4 mb-4 md:mb-6">
md lg и.т.д это брейкпоинты 

То есть md: mb-6 означает - для всех экранов >= md , то есть для md lg xl и 2xl

А mb-4 применится для экранов < md

Если ты хочешь обьявить класс для больших экранов нужно привязывать к большему брейкпоинту

Проверь пожалуйста по всему проекту

2024-08-01 08:04 UTC, Vladislav0Art commented on src/components/common/pet-project/PetProjectCard.tsx
> +            <div className="flex justify-between items-center gap-4 mb-4 md:mb-6">
Я это понимаю. 
При больших экранах верхняя секция карточки делает `margin-bottom` равным `6*4px` (как в макете). ПРи маленьких - `margin-bottom` ставится в `4*4px` (тоже как в макете).

Что в данном моменте не так?

2024-08-01 08:08 UTC, nikita-nn commented on src/components/common/pet-project/PetProjectCard.tsx
> +            <div className="flex justify-between items-center gap-4 mb-4 md:mb-6">
Под брейкпоинт md очень часто подходят мобильные устройства уровня IPhone 14 и выше / S20 и выше / и всякие айпады эйр , а также все десктопные устройства 

Зависит от твоей задумки - если так и должно быть - окей

2024-08-01 08:33 UTC, Vladislav0Art commented on src/components/common/pet-project/PetProjectCard.tsx
> +            <div className="flex justify-between items-center gap-4 mb-4 md:mb-6">
Я поиграюсь с `lg/md`. Возможно, `lg` уместнее местами будет.

2024-08-02 22:44 UTC, Vladislav0Art commented on src/components/common/pet-project/PetProjectCard.tsx
> +            <div className="flex justify-between items-center gap-4 mb-4 md:mb-6">
Местами поставил lg (для карточек pet-проектов).

2024-08-03 20:19 UTC, nikita-nn approved these changes

2024-08-03 20:19 UTC, nikita-nn commented on src/components/landing/how-it-works/HowItWorksSection.tsx
Не критично, но можно пропы если их не много деструктурировать прямо в стрелочный компонент

2024-08-03 21:19 UTC, merged