Implement "About" page and "Your possibilities" sections + NavBar
Pet-Plat/Pet-Platform-Front pull request #5
Opened 2024-08-01 20:38 UTC by nikita-nn

2024-08-02 22:49 UTC, Vladislav0Art commented on src/components/landing/about/AboutPetPlat.tsx
> +  return (
Тут не должен стоять тип `React.FC<void>`?

2024-08-02 23:23 UTC, Vladislav0Art requested changes
❗❗❗ **ATTENTION:** Мержишься в `master`; поменять на `stage`.

Оставил несколько комментариев по улучшению кода.

2024-08-02 23:23 UTC, Vladislav0Art commented on src/components/landing/navbar/NavBar.tsx
> +          </button>
"Зарегистрироваться" кнопка пропадает на ~lg, нельзя сделать регистрацию на всем, что `<=lg`.

![image](https://github.com/user-attachments/assets/3c6aacfb-c9ad-4317-af83-062400463894)

2024-08-02 23:23 UTC, Vladislav0Art commented on src/components/landing/navbar/NavBar.tsx
> +                ))}
Тут тоже может быть проблема с `key`, но в консоли не вижу ошибки.

2024-08-02 23:23 UTC, Vladislav0Art commented on src/components/landing/your-possibilities/YourPossibilities.tsx
> +  const cardLine =
Тип для функции `YourPossibilities`.

2024-08-02 23:23 UTC, Vladislav0Art commented on src/components/landing/your-possibilities/YourPossibilities.tsx
> +            className={
Тут тоже жалуется на `key` в консоли.

2024-08-02 23:23 UTC, Vladislav0Art commented on src/components/landing/your-possibilities/YourPossibilities.tsx
> +            </div>
Советую переписать на список строк `line`, вместо `line1`, `line2`. дубликации не будет + универсально для N bulletpoint'ов в карточке.

2024-08-02 23:23 UTC, Vladislav0Art commented on src/components/landing/your-possibilities/YourPossibilities.tsx
> +            </div>
+ можно вообще карточку как отдельный компонент сделать для читаемости кода.

2024-08-02 23:23 UTC, Vladislav0Art commented on src/components/ui/button.tsx
> +        // TODO: re-style other variants
Кнопка на главном экране огромная по размеру. Нужно использовать вот этот компонент, он уже стилизован под проект:

```
<Button>Выбрать проект</Button>
```

![image](https://github.com/user-attachments/assets/daf2720b-6674-4983-bf66-f284fbcc3d22)

2024-08-02 23:23 UTC, Vladislav0Art commented on src/components/ui/sheet.tsx
В чем отличие от `sheet.landing.tsx`?

2024-08-02 23:23 UTC, Vladislav0Art commented on src/data/links.ts
> +  {
Нужно задать тип.

2024-08-02 23:23 UTC, Vladislav0Art commented on src/data/possibilities.ts
> +    name: "Поиск проектов",
Тоже нужно задать тип.

2024-08-02 23:23 UTC, Vladislav0Art commented on src/data/possibilities.ts
> +      "Фильтры по языкам программирования, типам проектов и уровню сложности.",
Строки можно легко через список выразить. Лаконичнее и читабельнее будет.

2024-08-02 23:23 UTC, Vladislav0Art commented on src/views/pages/HomePage.tsx
> -  const [date, setDate] = useState<Date | undefined>(new Date());
Тут тоже надо ли тип ставить `React.FC<viod>`?

2024-08-02 23:23 UTC, Vladislav0Art commented on package.json
> +    "antd": "^5.19.4",
Где сейчас используется ant и зачем он нужен?

2024-08-02 23:23 UTC, Vladislav0Art commented on package.json
> +    "@radix-ui/react-dialog": "^1.1.1",
Это сейчас используется где-то?

2024-08-02 23:23 UTC, Vladislav0Art commented on src/components/landing/navbar/NavBar.tsx
Из-за того, что у `<a></a>` не установлен `href`, эти ссылки не имеют курсор pointer, а рендерятся как обычный текст. Поставь якоря на секции соответствующие (на те, что есть; остальные как заглушки `href="#"`):

![image](https://github.com/user-attachments/assets/3427f1dd-ae31-4737-bfde-f3181b4b94fb)

2024-08-03 06:15 UTC, nikita-nn commented on src/components/landing/navbar/NavBar.tsx
Пока что ссылок у нас нет - устанавливать их не нужно

2024-08-03 06:15 UTC, nikita-nn commented on package.json
> +    "@radix-ui/react-dialog": "^1.1.1",
ShadCN Sheet

2024-08-03 06:16 UTC, nikita-nn commented on package.json
> +    "antd": "^5.19.4",
Будет использоваться в виде компонента <Form> когда будем кодить регистрацию

2024-08-03 06:18 UTC, nikita-nn commented on src/views/pages/HomePage.tsx
> -  const [date, setDate] = useState<Date | undefined>(new Date());
Не нужно - React 18 позволяет обьявлять компоненты без указания типа

React.FC имеет смысл указывать если функция принимает пропсы

2024-08-03 06:19 UTC, nikita-nn commented on src/data/possibilities.ts
> +    name: "Поиск проектов",
Тип задан в функции которая этот массив принимает

Больше он нигде не используется

2024-08-03 06:19 UTC, nikita-nn commented on src/data/links.ts
> +  {
Тип задан в функции которая этот массив принимает

Больше он нигде не используется

2024-08-03 06:20 UTC, nikita-nn commented on src/components/ui/sheet.tsx
Изменено поведение кнопки закрытия + изменена высота самого sheetа

2024-08-03 06:21 UTC, nikita-nn commented on src/components/landing/your-possibilities/YourPossibilities.tsx
> +  const cardLine =
Не нужно - React 18 позволяет обьявлять компоненты без указания типа

React.FC имеет смысл указывать если функция принимает пропсы

2024-08-03 06:21 UTC, nikita-nn commented on src/components/landing/navbar/NavBar.tsx
> +          </button>
По макету ее тут быть не должно

2024-08-03 06:22 UTC, nikita-nn commented on src/components/landing/navbar/NavBar.tsx
> +    "border-[1px] border-white p-2 pl-5 pr-5 lg:p-6 lg:pt-3 lg:pb-3 rounded-full text-[1rem] hover:bg-[#ABABAB] duration-500 hover:text-black ";
duration time 1ms скорее всего неточность макета. Юзер не заметит разницу между 0ms и 1ms

2024-08-03 06:22 UTC, nikita-nn commented on src/components/ui/button.tsx
> +        // TODO: re-style other variants
Она такая только для md экранов , в том числе айпадов и больших мобильных устройств

2024-08-03 09:07 UTC, Vladislav0Art commented on src/components/landing/navbar/NavBar.tsx
> +          </button>
Тогда в макете недочет. Сообщаю Жене. Так как зарегаться никак нельзя сейчас.

2024-08-03 09:12 UTC, Vladislav0Art commented on src/components/ui/button.tsx
> +        // TODO: re-style other variants
Я тебе за это и говорю, зачем она такая большая, если этот компонент [components/ui/button.tsx](https://github.com/Pet-Plat/Pet-Platform-Front/pull/5/files/77b3a5b2d3f0e1f0ff91ca7eabdd031b8dd06b8c#diff-c29ec4c06502c45a9ee8740156618a5823f7cadbcd01a339304a66537c0dc30d) уже нормальный вид имеет. Поменять местами да и все, 5 секунд вопрос.

2024-08-03 09:20 UTC, Vladislav0Art commented on src/data/links.ts
> +  {
Тип динамически определяется от элементов массива, это все равно что с динамической типизацией писать. Если я сделаю `navBarLinks[0].link` типа `boolean`, то тип у меня вот такой будет:

![image](https://github.com/user-attachments/assets/8d149f33-a38f-4db6-86c2-fc7ceb92eeb2)

То есть я потенциально все, что захочу там могу указать -- все будет компилироваться, я даже не замечу, что где-то ошибка в данных, так как нет защиты элементов массива через тип.

> Тип задан в функции которая этот массив принимает
Тип задан элементами, которые лежат в массиве => этот тип может быть сколько угодно разный в зависимости от элементов.

Поставь тип `{ name: string, link: stirng }`, и проблема будет решена. Точно такая проблема для `possibilities` массива.

2024-08-03 09:21 UTC, Vladislav0Art commented on src/data/possibilities.ts
> +    name: "Поиск проектов",
Для `possibilities` массива вот такое изменение поведения, если указывать или не указывать тип (проблема та же, что для `navbarLinks`:

1. Указываю тип:

![with-type](https://github.com/user-attachments/assets/5f19d3dc-f07c-41d8-8395-d8567edebd65)

2. Не указываю тип: `line2` становиться объединением `string | boolean`:

![no-type-1](https://github.com/user-attachments/assets/7b2d68c0-7707-491c-b9cb-d2d1e20cfe02)
![no-type-2](https://github.com/user-attachments/assets/3a317556-930b-48a3-952a-4c80e195469a)

2024-08-03 09:24 UTC, Vladislav0Art commented on src/components/landing/navbar/NavBar.tsx
> +    "border-[1px] border-white p-2 pl-5 pr-5 lg:p-6 lg:pt-3 lg:pb-3 rounded-full text-[1rem] hover:bg-[#ABABAB] duration-500 hover:text-black ";
Принял, сообщу Жене. Замечание про цвета и hover/active состояния все еще в силе.

2024-08-03 09:25 UTC, Vladislav0Art commented on src/components/landing/navbar/NavBar.tsx
> +          </button>
Женя обновила макет, теперь в меню находится:

![image](https://github.com/user-attachments/assets/4aab0ec5-74e7-426d-8948-094c38a376f3)

2024-08-03 09:33 UTC, Vladislav0Art commented on src/components/landing/navbar/NavBar.tsx
Женя сказала, что это якорные ссылки -- на гелерею pet-проектов и "как это работает" ты уже можешь поставить якорь-ссылки. 

Прочитал, что `href` не обязательный атрибут, но без него `<a>` не воспринимается как hyperlink, тогда _[опционально]_ можешь на остальные `#` поставить, чтобы они как ссылки, а не текст рендерились.

2024-08-03 09:53 UTC, Vladislav0Art commented on src/components/landing/navbar/NavBar.tsx
Еще side-effect, если не указывать `href`: `<a>` больше нельзя взять в фокус через нажатия tab, они как текст обычных воспринимаются, а не как навигационных элемент.

2024-08-03 19:26 UTC, Vladislav0Art commented on src/components/landing/your-possibilities/YourPossibilities.tsx
> +            </div>
fixed.

2024-08-03 21:28 UTC, Vladislav0Art commented on src/components/ui/button.tsx
> +        // TODO: re-style other variants
Для Жени прикладываю, как маленькая кнопка выглядит:

![image](https://github.com/user-attachments/assets/1aaef0e8-e722-45f9-b8cd-86b15d224956)

2024-08-03 21:36 UTC, Vladislav0Art commented on src/components/ui/button.tsx
> +        // TODO: re-style other variants
Женя предложила маленькой сделать как на desktop.

2024-08-03 21:40 UTC, Vladislav0Art commented on src/components/landing/navbar/NavBar.tsx
> +    "border-[1px] border-white p-2 pl-5 pr-5 lg:p-6 lg:pt-3 lg:pb-3 rounded-full text-[1rem] hover:bg-[#ABABAB] duration-500 hover:text-black ";
Переоткрыл. Жду либо комментарий, либо изменение.

2024-08-03 21:46 UTC, Vladislav0Art commented on src/data/links.ts
> +}
👍🏻

2024-08-03 22:08 UTC, Vladislav0Art requested changes
Все норм. Жду update'ов по старым коментам; предложил небольшое улучшение для `localizeMe`.

2024-08-03 22:08 UTC, Vladislav0Art commented on src/hooks/localize.ts
> +    return enStr;
Как я понял, мы тут по сути проверяем, лежит ли `data` в `translations`; можно так сделать:
```javascript
if (...) { ... }
else {
  if (!Object.keys(translations).includes(data)) {
    throw new Error(`Translation module Error! '${data}' isn't in translations base`);
  }
  return data;
}
```

2024-08-04 07:57 UTC, Vladislav0Art approved these changes
Все норм, можно мержить.

2024-08-04 08:00 UTC, Vladislav0Art approved these changes

2024-08-04 08:21 UTC, merged