Implement "Join Us", "FAQ", and "Contacts" sections
Pet-Plat/Pet-Platform-Front pull request #8
Opened 2024-08-10 16:20 UTC by Vladislav0Art

# Описание изменений:
Добавляет указанные секции.

# Что-то не сделано:
Есть баг с шевроном для элемента в FAQ: я сделал его через `useState` внутри `accordinon.main.ts/AccordionTrigger`. На `onClick` меняю состояние с `rotated=false` на `rotated=true`. Баг в том, что если нажать на соседний элемент FAQ, то state для `rotated` не будет изменен и шеврон останется перевернутым. Со стандартным `ChevronDown` в [shadCN](https://ui.shadcn.com/docs/components/accordion#installation) такой проблемы нет -- он сам как-то понимает, что соседний элемент аккордиона был нажат. Стандартный по макету не подходит, поэтому надо как-то со своим такого же поведения добиться.

@nikita-nn **С указанным багом нужна помощь (коммит с твоей стороны или code snippet как исправить)**. Много времени потратил - не нашел как исправить.

# Health Check

* [x] **(_Если source-ветка это фича_) Я убедился, что делаю Pull Request в ветку `stage`**.
* [ ] **(_Если source-ветка это `stage`_) Я убедился, что делаю Pull Request в ветку `master`**.

2024-08-10 18:05 UTC, nikita-nn requested changes

2024-08-10 18:05 UTC, nikita-nn commented on src/components/landing/contacts/Contacts.tsx
> +   const iconsClasses = "w-[30px] md:w-[40px]"
Если будешь эти классы использовать в будущем не только в этом файле,  пожалуйста вынеси их в globals.css 

@layer components

2024-08-10 18:05 UTC, nikita-nn commented on src/styles/globals.css
Лучше все ширины/высоты указывать в относительных величинах - например rem

2024-08-10 18:05 UTC, nikita-nn commented on src/components/landing/join-us/JoinUsSection.tsx
Я указывал размеры текста для всех видов заголовков в globals.css ( @layer base ) - если это обычный заголовок , указывать величины необязательно

2024-08-10 18:06 UTC, nikita-nn requested changes

2024-08-10 18:06 UTC, nikita-nn commented on src/components/landing/join-us/JoinUsSection.tsx
> +
Я указывал размеры текста для всех видов заголовков в globals.css ( https://github.com/layer base ) - если это обычный заголовок , указывать величины необязательно

2024-08-10 18:09 UTC, nikita-nn requested changes

2024-08-10 18:09 UTC, nikita-nn commented on src/styles/globals.css
> +    height: 1px;
лучше указывать ширины / высоты в относительных величинах ,например rem

2024-08-12 20:59 UTC, Vladislav0Art commented on src/components/landing/contacts/Contacts.tsx
> +   const iconsClasses = "w-[30px] md:w-[40px]"
Эти классы только для ссылок в блоке `Contacts` используются. Этот блок по стилям отличается от остальных, и пока в дизайне нет элементов с чем-то схожим. Выносил в переменные только чтобы не дублировать для классы для ссылок и иконок `Telegram` и `Email`. 

Поэтому это сугубо локальные стили. Не планировал их на что-то другое применять, да и не на что.

2024-08-12 21:18 UTC, Vladislav0Art commented on src/components/landing/join-us/JoinUsSection.tsx
> +
Обратил внимание. 
Я по макету посмотрел: текущий стиль для `h3` для мобилок был меньше нужного (16 вместо 18). Сделал старый стиль для `h4`, и дописал новый для `h3` согласно дизайну. Где надо, поставил тег `h3` и с имеющихся `h3` (пару место было; коммит [f9b18ac](https://github.com/Pet-Plat/Pet-Platform-Front/pull/8/commits/f9b18acdb87d93f8d4defbbeade0327c8f97356f)) убрал текстовые стили.

2024-08-12 21:24 UTC, Vladislav0Art commented on src/styles/globals.css
> +    height: 1px;
Перевел в `rem`.

2024-08-12 21:32 UTC, nikita-nn requested changes

2024-08-12 21:32 UTC, nikita-nn commented on src/components/common/pet-project/PetProjectCard.tsx
> -        <h3 className="text-lg font-bold mb-2 sm:text-2xl sm:mb-4">
Я переопределял стандартные html теги , то есть можно использовать просто h3 с нужными стилями, которые не указаны в globals.css (или если очень хочется переопределить их в className)

Пример:

globals.css
```
h3{
  @apply класс1 класс2
}
```

file.tsx
```
<h3 className={"класс3"}>какой то текст</h3>
```

В этом случае h3 уже будет иметь в className класс1 ,класс2 и класс3

Так как класс1 и класс2 были установлены глобально

2024-08-12 21:32 UTC, nikita-nn commented on src/components/landing/about/AboutPetPlat.tsx
> +        <p className="sm:text-2xl">
Тоже самое что в комментарии выше

2024-08-12 21:32 UTC, nikita-nn commented on src/components/landing/how-it-works/HowItWorksCard.tsx
> -      <h4 className="text-lg font-bold mb-2 md:text-2xl md:mb-4">{title}</h4>
Тоже самое

2024-08-19 20:19 UTC, Vladislav0Art commented on src/components/common/pet-project/PetProjectCard.tsx
> -        <h3 className="text-lg font-bold mb-2 sm:text-2xl sm:mb-4">
Погоди, ты комментарий оставил на удаленной строке (красное). То, что ты выше написал, я понимаю, и на основании этого подгонял стили проекта. Т.е., эта правка внесена ранее.

Сейчас все `h3`, что есть в проекте, такие (ни один не имеет доп стилей font'a):
```html
<h3 className="mb-2 md:mb-4">{title}</h3>
```

```html
<h3 className="mb-2 sm:mb-4">{data.name}</h3>
```

```html
<h3 className="text-center">Присоединяйтесь к <br className="sm:hidden" /> Pet-Plat в Telegram!</h3>
```

```html
<h3>{possibility.name}</h3>
```

2024-08-19 21:31 UTC, Vladislav0Art commented on src/components/landing/about/AboutPetPlat.tsx
> +        <p className="sm:text-2xl">
Этот элемент - исключение. Это единственный `<p>`, который имеет больший размер по сравнению с остальными, так как он в main screen'е под title'ом. Ему просто не сопоставить никакой pre-defined стиль, так как он такой один.

Посмотрел на все `<p>`, что были в проекте, у них у всех писался один и тот же стиль: `text-sm sm:text-base`. Обновил в `globals.css` и поснимал стили с этих `<p>`-тегов. Теперь чуть побольше re-use'а.

2024-08-19 21:32 UTC, Vladislav0Art commented on src/components/landing/how-it-works/HowItWorksCard.tsx
> -      <h4 className="text-lg font-bold mb-2 md:text-2xl md:mb-4">{title}</h4>
Тут тоже на красное коммент, это удаленная строка.
Или ты про другой участок (не выделился)?

2024-08-24 18:47 UTC, nikita-nn approved these changes

2024-08-25 06:25 UTC, merged